// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    ChannelHeading: typeof import('./src/components/ChannelHeading.vue')['default']
    ChannelItem: typeof import('./src/components/ChannelItem.vue')['default']
    ChannelVideoItem: typeof import('./src/components/ChannelVideoItem.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    LogoNew: typeof import('./src/components/LogoNew.vue')['default']
    LogoV2: typeof import('./src/components/LogoV2.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    RegularButton: typeof import('./src/components/RegularButton.vue')['default']
    RevealButton: typeof import('./src/components/RevealButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    UserSubscriptions: typeof import('./src/components/UserSubscriptions.vue')['default']
    VideoComments: typeof import('./src/components/VideoComments.vue')['default']
    VideoItem: typeof import('./src/components/VideoItem.vue')['default']
    VideoItemHorizontal: typeof import('./src/components/VideoItemHorizontal.vue')['default']
  }
}

export {}
